config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  resources :books, only: [:new, :create, :index, :show, :edit, :destroy, :update] do
    resource :favorites, only: [:create, :destroy]
  end
  resources :users, only: [:index, :show, :edit, :update]
  get "home/about" => "homes#about", as: "about"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base

  self.abstract_class = true

end

app/models/book.rb
class Book < ApplicationRecord

  has_one_attached :profile_image
  belongs_to :user
  has_many :favorites,dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }


    def get_profile_image(width, height)
     unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
     end
     profile_image.variant(resize_to_limit: [width, height]).processed
    end

   def favorited_by?(user)
    favorites.exists?(user_id: user.id)
   end

end

app/models/favorite.rb
class Favorite < ApplicationRecord

    belongs_to :user
    belongs_to :book

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

   has_one_attached :profile_image
   has_many :books, dependent: :destroy
   has_many :favorites, dependent: :destroy

   validates :name, uniqueness: true, length: { minimum: 2, maximum: 20 }
   validates :introduction, length: { maximum: 50 }

   def get_profile_image(width, height)
     unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
     end
     profile_image.variant(resize_to_limit: [width, height]).processed
   end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 before_action :authenticate_user!, except: [:top, :about]
 before_action :configure_permitted_parameters, if: :devise_controller?

   def after_sign_in_path_for(resource)
    user_path(current_user)
   end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up,keys:[:email])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
before_action :correct_user, only: [:edit, :update]

  def new
  end

  def index
    @book = Book.new
    @books = Book.all
    @user = current_user
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @user = current_user
      @books = Book.all
      render :index
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end



  def show
    @new_book = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
   if @book.update(book_params)
     flash[:notice] = "You have created book successfully."
    redirect_to book_path(@book.id)
   else
    @books = Book.all
    render :edit
   end
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def correct_user
    @book = Book.find(params[:id])
    @user = @book.user
    redirect_to(books_path) unless @user == current_user
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

 def create
  book = Book.find(params[:book_id])
  favorite = current_user.favorites.new(book_id: book.id)
  favorite.save
  redirect_to books_path
 end

 def destroy
  book = Book.find(params[:book_id])
  favorite = current_user.favorites.find_by(book_id: book.id)
  favorite.destroy
  redirect_to books_path
 end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :is_matching_login_user, only: [:edit, :update]

  def index
    @users = User.all
    @book = Book.new
    @user = current_user
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new

  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
   if @user.update(user_params)
     flash[:notice] = "You have updated user successfully."
     redirect_to user_path(@user.id)
   else
     @users = User.all
     render :edit
   end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def is_matching_login_user
    user_id = params[:id].to_i
    unless user_id == current_user.id
      redirect_to user_path(current_user)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<div class="container px-5 px-sm-0">
 <div class="row">
  <div class="col-md-3">
   <h1>User info</h1>
   <%= image_tag user.get_profile_image(100,100) %>
　  <table class="table">
　　 <tbody>
      <tr>
      </tr>
      <tr>
       <th>name</th>
       <th>
         <%= user.name %>
       </th>
      </tr>
      <tr>
       <th>introduction</th>
       <th><%= user.introduction %></th>
      </tr>
  　  </tbody>
　  </table>

      <%= link_to edit_user_path(user), class: 'btn btn-outline-secondary btn-block' do %>
       <i class="fas fa-user-cog"></i>
      <% end %>


      <h2>New book</h2>
      <%= form_with model: book do |f| %>
      <div class="form-group">
       <p>Title</p>
        <%= f.text_field :title, class:"form-control" %>
      </div>
      <div class="form-group">
        <p>Opinion</p>
        <%= f.text_area :body, class:"form-control" %><br>
      </div>
      <div class="form-group">
        <%= f.submit 'Create Book', class: 'btn btn-success btn-lg' %>
      <% end %>
      </div>
    </div>

app/views/books/edit.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
     <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
      <%= form_with model: @book do |f| %>

       <div class="form-group">
        <p>Title</p>
        <%= f.text_field :title, class: "form-control" %>
       </div>
       <div class="form-group">
        <p>Opinion</p>
        <%= f.text_area :body, class: "form-control" %><br>
       </div>
       <div class="form-group">
        <input type="submit" name="commit" value="Update Book" class="btn btn-success" data-disable-with="Update Book">
       </div>

      <% end %>

<%= link_to "Show", book_path(@book.id) %>
|
<%= link_to "Back", books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<%= flash[:notice] %>

<%= render 'list', book: @book, user: @user %>

  <div class="col-md-8 offset-md-1">
   <h2>Books</h2>
   <table class="table table-hover table-inverse">
    <thead>
     <tr>
       <th></th>
       <th>Title</th>
       <th>Opinion</th>
     </tr>
    </thead>
    <tbody>
    <% @books.each do |book| %>
     <tr>
       <td>
         <%= link_to user_path(book.user.id) do %>
          <%= image_tag book.user.get_profile_image(100,100) %>
         <% end %>
       </td>
       <td>
         <%= link_to book_path(book.id) do %>
         <%= book.title %>
         <% end %>
       </td>
       <td><%= book.body %></td>
       <td>
       <% if book.favorited_by?(current_user) %>
        <%= link_to book_favorites_path(book), method: :delete do %>
         ♥<%= book.favorites.count %>
        <% end %>
        <% else %>
        <%= link_to book_favorites_path(book), method: :post do %>
         ♥<%= book.favorites.count %>
        <% end %>
       <% end %>
       </td>
     </tr>
    <% end %>
   </tbody>
  </table>

  </div>
 </div>
</div>

app/views/books/show.html.erb
<%= render 'list', book: @new_book, user: @user %>

  <div class="col-md-8 offset-md-1">
   <h1>Book detail</h1>
   <table class="table">
    <tbody>
     <tr>
      <td>
         <%= link_to user_path(@book.user.id) do %>
          <%= image_tag @book.user.get_profile_image(100,100) %><br>
          <%= @book.user.name %>
         <% end %>
       </td>
       <td>
         <%= link_to book_path(@book.id) do %>
          <%= @book.title %>
         <% end %>
       </td>
       <td><%= @book.body %></td>
       <td>
         <% if @book.user == current_user %>
         <%= link_to "Edit",edit_book_path(@book), class:"btn btn-sm btn-success" %>
         <% end %>
       </td>
       <td>
         <% if @book.user == current_user %>
         <%= link_to "Destroy", book_path(@book), method: :delete, class:"btn btn-sm btn-danger" %>
         <% end %>
      </td>
      <th>
       <% if @book.favorited_by?(current_user) %>
        <%= link_to book_favorites_path(@book), method: :delete do %>
         ♥<%= @book.favorites.count %>
        <% end %>
        <% else %>
        <%= link_to book_favorites_path(@book), method: :post do %>
         ♥<%= @book.favorites.count %>
        <% end %>
       <% end %>
      </th>
     </tr>
    </tbody>
   </table>
  </div>
 </div>
</div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <div class="px-3 mx-auto">
        <h1>Welcome to <i class="fas fa-book"></i>Bookers!</h1>
    </div>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class="fas fa-book"></i>Bookers !!</h1>
       <p>In <i class="fas fa-book"></i>Bookers,</p>

       <p>you can share and exchange your opinions , inpressions , and emotions</p>
       <p>about various books!</p>

       <div class="btn-wrapper col-10 mx-auto">
         <div class="row">
           <%= link_to "Log in", new_user_session_path, class: 'btn btn-info btn-sm btn-block md-3' %>
         </div>
         <div class="row">
           <%= link_to "Sign up", new_user_registration_path, class: 'btn btn-success btn-sm btn-block' %>
         </div>
       </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
   <header class="shadow-sm">
     <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
       <div class="container">
         <a class="navbar-brand" href="/">Bookers</a>
         <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
       </button>
      <div class="navbar-collapse collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to  user_path(current_user.id), class: 'nav-link text-light' do %>
            <i class="fas fa-home"></i>
            Home
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to  users_path, class: 'nav-link text-light' do %>
            <i class="fas fa-users"></i>
            Users
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to  books_path, class: 'nav-link text-light' do %>
            <i class="fas fa-book-open"></i>
            Books
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to  destroy_user_session_path, method: :delete, class: 'nav-link text-light' do %>
            <i class="fas fa-sign-out-alt"></i>
            Log out
            <% end %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to root_path,class: 'nav-link text-light' do %>
            <i class="fas fa-home"></i>
            Home
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to about_path,class: 'nav-link text-light' do %>
            <i class="fas fa-link"></i>
            About
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to new_user_registration_path,class: 'nav-link text-light' do %>
            <i class="fas fa-user-plus"></i>
            Sign up
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to new_user_session_path,class: 'nav-link text-light' do %>
            <i class="fas fa-sign-in-alt"></i>
            Log in
            <% end %>
          </li>

          <% end %>
        </ul>
      </div>
     </nav>
   </header>
   <main>
     <%= flash[:notice] %>
     
    <%= yield %>
   </main>
   <footer>
     <div class="container mt-5">
      <div class="row">
        <div class="mx-auto">
          <p>CopyRight Infratop.inc</p>
        </div>
      </div>
     </div>
   </footer>
  </body>
</html>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <%= @user.errors.count %>errors prohibited this obj from being saved:
    <ul>
     <% @user.errors.full_messages.each do |message| %>
       <li><%= message %></li>
     <% end %>
    </ul>
<% end %>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
      <%= form_with model: @user do |f| %>
       <div class="form-group">
        <label for="user_Name">Name</label>
        <%= f.text_field :name,autofocus: true, id:"user_Name", class: "form-control" %>
       </div>
       <div class="form-group">
        <label for="user_profile_image">Image</label><br>
        <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>
       </div>
       <div class="form-group">
        <label for="user_Introduction">Introduction</label>
        <%= f.text_area :introduction,autofocus: true, id:"user_Introduction", class: "form-control" %>
       </div>
       <div class="form-group">
        <input type="submit" name="commit" value="Update User" class="btn btn-secondary" data-disable-with="Update User">
       </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<%= render 'books/list', book: @book, user: @user %>

    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table">
       <thead>
        <tr>
         <th>image</th>
         <th>name</th>
         <th></th>
        </tr>
      </thead>
      <tbody>
      <% @users.each do |user| %>
        <tr>
         <td>
          <%= image_tag user.get_profile_image(100,100) %>
         </td>
         <td><%= user.name %></td>
         <td><%= link_to "Show",user_path(user.id) %></td>
        </tr>
       <% end %>
       </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<%= render 'books/list', book: @book, user: @user %>

    <div class="col-md-8 offset-md-1">
      <h1>Books</h1>
      <table class="table">
       <thead>
         <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th colspan="3"></th>
         </tr>
       </thead>
       <tbody>
       <% @books.each do |book| %>
       <tr>
        <td>
          <%= link_to user_path(@user.id) do %>
          <%= image_tag book.user.get_profile_image(100,100) %>
          <% end %>
        </td>
        <td>
         <%= link_to book_path(book.id) do %>
         <%= book.title %>
         <% end %>
        </td>
        <td><%= book.body %></td>
       </tr>
       <% end %>
      </tbody>
     </table>
    </div>
  </div>
</div>